# Site settings
author: Anthony Ybarra
title: Anthony's Coding Journey
header-img: img/home-bg.png
email: anthony_jy72@yahoo.com
copyright_name: Anthony Ybarra
description: > # this means to ignore newlines until "baseurl:"
  My trek through coding bootcamp
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  Anthonyjy72

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
